"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { GitCompare, Upload, FileText, Download, AlertTriangle, X } from "lucide-react";
import dynamic from "next/dynamic";
import { Schema } from "@/lib/generateSQL";

// Dynamically import Monaco Editor to avoid SSR issues
const Editor = dynamic(() => import("@monaco-editor/react"), { ssr: false });

interface MigrationGeneratorProps {
  currentSchema: Schema;
  dialect: string;
  apiUrl: string;
}

interface MigrationResult {
  sql: string;
  additions: number;
  modifications: number;
  destructive: number;
}

export default function MigrationGenerator({ currentSchema, dialect, apiUrl }: MigrationGeneratorProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [mode, setMode] = useState<"upload" | "paste">("upload");
  const [pastedSQL, setPastedSQL] = useState("");
  const [oldSchema, setOldSchema] = useState<Schema | null>(null);
  const [migration, setMigration] = useState<MigrationResult | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setIsProcessing(true);
    setError(null);

    const formData = new FormData();
    formData.append("file", file);
    formData.append("dialect", dialect);

    try {
      if (!apiUrl) {
        throw new Error("API URL is not configured. Please check your environment variables.");
      }

      const res = await fetch(`${apiUrl}/api/generate`, {
        method: "POST",
        body: formData,
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.message || "Failed to extract schema");

      setOldSchema(data.raw_schema);
      const migrationResult = generateMigration(data.raw_schema, currentSchema, dialect);
      setMigration(migrationResult);
    } catch (err: any) {
      setError(err.message || "Failed to process image");
    } finally {
      setIsProcessing(false);
    }
  };

  const handlePasteSQL = () => {
    if (!pastedSQL.trim()) {
      setError("Please paste SQL code");
      return;
    }

    setIsProcessing(true);
    setError(null);

    try {
      // Parse SQL to extract schema (simplified parser)
      const parsedSchema = parseSQLToSchema(pastedSQL);
      setOldSchema(parsedSchema);
      const migrationResult = generateMigration(parsedSchema, currentSchema, dialect);
      setMigration(migrationResult);
    } catch (err: any) {
      setError(err.message || "Failed to parse SQL");
    } finally {
      setIsProcessing(false);
    }
  };

  const handleDownloadMigration = () => {
    if (!migration) return;

    const header = `-- Migration Script
-- Generated by Whiteboard Architect
-- Dialect: ${dialect}
-- Date: ${new Date().toLocaleString()}
-- Summary: ${migration.additions} additions, ${migration.modifications} modifications, ${migration.destructive} destructive operations

`;

    const fullContent = header + migration.sql;

    const blob = new Blob([fullContent], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "migration.sql";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleClose = () => {
    setIsOpen(false);
    setOldSchema(null);
    setMigration(null);
    setPastedSQL("");
    setError(null);
  };

  return (
    <>
      {/* Trigger Button */}
      <button
        onClick={() => setIsOpen(true)}
        className="px-4 py-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-md text-xs font-medium text-white transition-colors flex items-center gap-2"
      >
        <GitCompare className="w-3.5 h-3.5 text-primary" />
        Generate Migration
      </button>

      {/* Modal */}
      <AnimatePresence>
        {isOpen && (
          <>
            {/* Backdrop */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={handleClose}
              className="fixed inset-0 bg-black/60 backdrop-blur-sm z-[200]"
            />

            {/* Panel */}
            <motion.div
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: 50 }}
              transition={{ type: "spring", damping: 25, stiffness: 300 }}
              className="fixed inset-x-4 bottom-4 top-20 z-[210] bg-[#0F0F11] border border-white/10 rounded-2xl shadow-2xl overflow-hidden flex flex-col"
            >
              {/* Header */}
              <div className="flex items-center justify-between px-6 py-4 border-b border-white/10 bg-[#0A0A0C]">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-primary/20 flex items-center justify-center">
                    <GitCompare className="w-5 h-5 text-primary" />
                  </div>
                  <div>
                    <h2 className="text-lg font-bold text-white">Schema Migration Generator</h2>
                    <p className="text-xs text-gray-500">Compare schemas and generate ALTER statements</p>
                  </div>
                </div>
                <button
                  onClick={handleClose}
                  className="p-2 hover:bg-white/5 rounded-full text-gray-400 hover:text-white transition-colors"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              {/* Body */}
              <div className="flex-1 overflow-hidden flex flex-col lg:flex-row">
                {/* Left: Input Section */}
                <div className="lg:w-1/3 border-b lg:border-b-0 lg:border-r border-white/10 p-6 space-y-4 overflow-y-auto">
                  <div>
                    <h3 className="text-sm font-semibold text-white mb-3">Previous Schema Source</h3>
                    <div className="flex gap-2 mb-4">
                      <button
                        onClick={() => setMode("upload")}
                        className={`flex-1 px-3 py-2 rounded-lg text-xs font-medium transition-colors ${
                          mode === "upload"
                            ? "bg-primary/20 text-primary border border-primary/40"
                            : "bg-white/5 text-gray-400 border border-white/10 hover:bg-white/10"
                        }`}
                      >
                        <Upload className="w-4 h-4 mx-auto mb-1" />
                        Upload Image
                      </button>
                      <button
                        onClick={() => setMode("paste")}
                        className={`flex-1 px-3 py-2 rounded-lg text-xs font-medium transition-colors ${
                          mode === "paste"
                            ? "bg-primary/20 text-primary border border-primary/40"
                            : "bg-white/5 text-gray-400 border border-white/10 hover:bg-white/10"
                        }`}
                      >
                        <FileText className="w-4 h-4 mx-auto mb-1" />
                        Paste SQL
                      </button>
                    </div>

                    {mode === "upload" ? (
                      <label className="block cursor-pointer">
                        <input
                          type="file"
                          accept="image/*"
                          className="hidden"
                          onChange={handleFileUpload}
                          disabled={isProcessing}
                        />
                        <div className="p-6 border-2 border-dashed border-white/10 hover:border-primary/50 rounded-lg bg-white/[0.01] hover:bg-white/[0.03] transition-all text-center">
                          <Upload className="w-8 h-8 mx-auto mb-2 text-gray-400" />
                          <p className="text-xs text-gray-400">Click to upload whiteboard image</p>
                        </div>
                      </label>
                    ) : (
                      <div className="space-y-2">
                        <textarea
                          value={pastedSQL}
                          onChange={(e) => setPastedSQL(e.target.value)}
                          placeholder="Paste your SQL DDL here..."
                          className="w-full h-40 px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary/50 font-mono text-xs resize-none"
                          disabled={isProcessing}
                        />
                        <button
                          onClick={handlePasteSQL}
                          disabled={isProcessing || !pastedSQL.trim()}
                          className="w-full px-4 py-2 bg-primary hover:bg-primary/90 rounded-lg text-sm font-semibold text-white transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                          {isProcessing ? "Processing..." : "Compare Schemas"}
                        </button>
                      </div>
                    )}
                  </div>

                  {error && (
                    <div className="p-3 bg-red-500/10 border border-red-500/30 rounded-lg flex items-start gap-2">
                      <AlertTriangle className="w-4 h-4 text-red-400 flex-shrink-0 mt-0.5" />
                      <p className="text-xs text-red-200">{error}</p>
                    </div>
                  )}

                  {migration && (
                    <div className="p-4 bg-white/5 border border-white/10 rounded-lg space-y-2">
                      <h4 className="text-xs font-semibold text-white mb-2">Migration Summary</h4>
                      <div className="space-y-1 text-xs">
                        <div className="flex justify-between">
                          <span className="text-gray-400">Additions:</span>
                          <span className="text-green-400 font-mono">{migration.additions}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-gray-400">Modifications:</span>
                          <span className="text-blue-400 font-mono">{migration.modifications}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-gray-400">Destructive:</span>
                          <span className="text-red-400 font-mono">{migration.destructive}</span>
                        </div>
                      </div>
                      <button
                        onClick={handleDownloadMigration}
                        className="w-full mt-3 px-3 py-2 bg-primary/20 hover:bg-primary/30 border border-primary/40 rounded-lg text-xs font-medium text-primary transition-colors flex items-center justify-center gap-2"
                      >
                        <Download className="w-3.5 h-3.5" />
                        Download migration.sql
                      </button>
                    </div>
                  )}
                </div>

                {/* Right: Migration SQL Display */}
                <div className="flex-1 flex flex-col bg-[#050505]">
                  {migration ? (
                    <Editor
                      height="100%"
                      defaultLanguage="sql"
                      value={migration.sql}
                      theme="vs-dark"
                      options={{
                        readOnly: true,
                        minimap: { enabled: false },
                        fontSize: 13,
                        lineHeight: 22,
                        fontFamily: "JetBrains Mono, ui-monospace, monospace",
                        padding: { top: 20, bottom: 20 },
                        scrollBeyondLastLine: false,
                      }}
                    />
                  ) : (
                    <div className="flex-1 flex items-center justify-center text-gray-500 text-sm">
                      Upload or paste a previous schema to generate migration SQL
                    </div>
                  )}
                </div>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </>
  );
}

/**
 * Generate migration SQL by comparing old and new schemas
 */
function generateMigration(oldSchema: Schema, newSchema: Schema, dialect: string): MigrationResult {
  let sql = "";
  let additions = 0;
  let modifications = 0;
  let destructive = 0;

  const oldTables = new Map(oldSchema.tables.map((t) => [t.name, t]));
  const newTables = new Map(newSchema.tables.map((t) => [t.name, t]));

  // Detect dropped tables
  oldTables.forEach((oldTable, tableName) => {
    if (!newTables.has(tableName)) {
      sql += `-- ⚠ DESTRUCTIVE: Dropping table\nDROP TABLE IF EXISTS ${tableName};\n\n`;
      destructive++;
    }
  });

  // Detect new tables and modified tables
  newTables.forEach((newTable, tableName) => {
    const oldTable = oldTables.get(tableName);

    if (!oldTable) {
      // New table
      sql += `-- Adding new table: ${tableName}\nCREATE TABLE ${tableName} (\n`;
      const colDefs = newTable.columns.map((col) => `  ${col.name} ${col.type}`);
      sql += colDefs.join(",\n");
      sql += "\n);\n\n";
      additions++;
    } else {
      // Compare columns
      const oldCols = new Map(oldTable.columns.map((c) => [c.name, c]));
      const newCols = new Map(newTable.columns.map((c) => [c.name, c]));

      // Dropped columns
      oldCols.forEach((oldCol, colName) => {
        if (!newCols.has(colName)) {
          sql += `-- ⚠ DESTRUCTIVE: Dropping column\nALTER TABLE ${tableName} DROP COLUMN ${colName};\n\n`;
          destructive++;
        }
      });

      // Added or modified columns
      newCols.forEach((newCol, colName) => {
        const oldCol = oldCols.get(colName);

        if (!oldCol) {
          // New column
          sql += `ALTER TABLE ${tableName} ADD COLUMN ${colName} ${newCol.type};\n\n`;
          additions++;
        } else if (oldCol.type !== newCol.type) {
          // Type changed
          if (dialect === "mysql" || dialect === "planetscale") {
            sql += `ALTER TABLE ${tableName} MODIFY COLUMN ${colName} ${newCol.type};\n\n`;
          } else {
            sql += `ALTER TABLE ${tableName} ALTER COLUMN ${colName} TYPE ${newCol.type};\n\n`;
          }
          modifications++;
        }
      });

      // Detect renames (heuristic: similar names)
      oldCols.forEach((oldCol, oldName) => {
        if (!newCols.has(oldName)) {
          newCols.forEach((newCol, newName) => {
            if (!oldCols.has(newName) && similarity(oldName, newName) > 0.6) {
              sql += `-- Manual rename required: ${oldName} → ${newName}\n\n`;
            }
          });
        }
      });
    }
  });

  if (sql === "") {
    sql = "-- No changes detected between schemas\n";
  }

  return { sql, additions, modifications, destructive };
}

/**
 * Simple SQL parser to extract schema from DDL
 */
function parseSQLToSchema(sql: string): Schema {
  const tables: any[] = [];
  const createTableRegex = /CREATE\s+TABLE\s+(\w+)\s*\(([\s\S]*?)\);/gi;

  let match;
  while ((match = createTableRegex.exec(sql)) !== null) {
    const tableName = match[1];
    const columnBlock = match[2];

    const columns: any[] = [];
    const lines = columnBlock.split(",").map((l) => l.trim());

    lines.forEach((line) => {
      const colMatch = line.match(/^(\w+)\s+(\w+(\(\d+\))?)/i);
      if (colMatch) {
        const colName = colMatch[1];
        const colType = colMatch[2];
        const isPK = /PRIMARY KEY/i.test(line);
        const isFK = /REFERENCES/i.test(line);

        columns.push({
          name: colName,
          type: colType,
          is_primary_key: isPK,
          is_foreign_key: isFK,
          foreign_key_target: "",
        });
      }
    });

    tables.push({ name: tableName, columns });
  }

  return { tables };
}

/**
 * String similarity (Levenshtein-based)
 */
function similarity(s1: string, s2: string): number {
  const longer = s1.length > s2.length ? s1 : s2;
  const shorter = s1.length > s2.length ? s2 : s1;
  if (longer.length === 0) return 1.0;
  const editDistance = levenshtein(longer, shorter);
  return (longer.length - editDistance) / longer.length;
}

function levenshtein(s1: string, s2: string): number {
  const costs: number[] = [];
  for (let i = 0; i <= s1.length; i++) {
    let lastValue = i;
    for (let j = 0; j <= s2.length; j++) {
      if (i === 0) {
        costs[j] = j;
      } else if (j > 0) {
        let newValue = costs[j - 1];
        if (s1.charAt(i - 1) !== s2.charAt(j - 1)) {
          newValue = Math.min(Math.min(newValue, lastValue), costs[j]) + 1;
        }
        costs[j - 1] = lastValue;
        lastValue = newValue;
      }
    }
    if (i > 0) costs[s2.length] = lastValue;
  }
  return costs[s2.length];
}
