/**
 * Downloads SQL code as a .sql file with a header comment
 */
export function downloadSQL(sqlCode: string, dialect: string): void {
  const now = new Date();
  const dateString = now.toLocaleString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  const header = `-- Generated by Whiteboard Architect
-- Dialect: ${dialect}
-- Date: ${dateString}

`;

  const fullContent = header + sqlCode;

  // Create blob and trigger download
  const blob = new Blob([fullContent], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = "schema.sql";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
